@PokeServer_HostAddress = http://localhost:5190


@DeckId=0
GET {{PokeServer_HostAddress}}/game/getnewgame/{{DeckId}}


###
@Guid=667d2c30-2163-4207-b361-cbcd8e4b2448
GET {{PokeServer_HostAddress}}/game/checkgameactive/{{guid}}

###

GET {{PokeServer_HostAddress}}/game/drawcardfromdeck/{{guid}}

###


PUT {{PokeServer_HostAddress}}/game/discardcard/{{guid}}
Content-Type: application/json

{
  "$type": "EnergyCard",
  "effect": "",
  "energyType": "Normal",
  "energyColor": "",
  "numberInDeck": "746fc404-b926-4e89-a361-3aa0b23fcf74",
  "category": "Energy",
  "id": "base1-97",
  "image": "https://assets.tcgdex.net/en/base/base1/97",
  "name": "Fighting Energy",
  "description": ""
}


###

PUT {{PokeServer_HostAddress}}/game/endgame/{{guid}}

###

GET {{PokeServer_HostAddress}}/game/flipcoin

###

@x=15
GET {{PokeServer_HostAddress}}/game/flipxcoins/{{x}}

###

@isHeads=False
GET {{PokeServer_HostAddress}}/game/flipcoinsuntil/{{isHeads}}

###

GET {{PokeServer_HostAddress}}/game/drawcardfromprizes/{{guid}}

###
