@PokeServer_HostAddress = http://localhost:5190


@DeckId=0
GET {{PokeServer_HostAddress}}/game/getnewgame/{{DeckId}}


###
@Guid=8d97c403-b21b-43d3-b46b-059ca55c8996
GET {{PokeServer_HostAddress}}/game/checkgameactive/{{guid}}

###

GET {{PokeServer_HostAddress}}/game/drawcardfromdeck/{{guid}}

###


PUT {{PokeServer_HostAddress}}/game/discardcard/{{guid}}
Content-Type: application/json

{
  // Card
}


###

PUT {{PokeServer_HostAddress}}/game/endgame/{{guid}}

###

GET {{PokeServer_HostAddress}}/game/flipcoin

###

@x=5
GET {{PokeServer_HostAddress}}/game/flipxcoins/{{x}}

###

@isHeads=False
GET {{PokeServer_HostAddress}}/game/flipcoinsuntil/{{isHeads}}

###

GET {{PokeServer_HostAddress}}/game/drawcardfromprizes/{{guid}}

###
